apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivolve-app 
spec:
  template:
    spec:
      containers:
      - name: ivolve-container
        image: 747034604314.dkr.ecr.eu-central-1.amazonaws.com/finalproject-ivolve-repo:v7

