apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: image-patch.yaml
  - path: replicas-patch.yaml
  - path: ns-patch.yaml
  - path: lb-patch.yaml
